config/routes.rb
Rails.application.routes.draw do
  devise_for :coaches

  root 'coaches#index'
  resources :meets, only: [:show, :update]
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :team
  has_many :swimmers, through: :team, source: :swimmers
end

app/models/meet.rb
class Meet < ActiveRecord::Base
  
  has_many :entries
  has_many :swimmers, through: :entries, source: :swimmer
  has_many :teams, -> { uniq }, through: :swimmers
end

app/models/swim_event.rb
class SwimEvent < ActiveRecord::Base
  has_many :swimmer_entries
  has_many :swimmers, through: :swimmer_entries, source: :swimmer
end

app/models/swimmer.rb
class Swimmer < ActiveRecord::Base
  belongs_to :team
end

app/models/swimmer_entry.rb
class SwimmerEntry < ActiveRecord::Base
  belongs_to :meet
  belongs_to :swimmer
  belongs_to :swim_event
end

app/models/team.rb
class Team < ActiveRecord::Base

  has_many :coaches
  has_many :swimmers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController

  def index
    @coach = current_coach
    @meets = Meet.all
  end

end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController

  def show
    # fail
    @meet = Meet.find(params[:id])
  end

  def update
    @meet = Meet.find(params[:id])
    fail
    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    return <<-HTML.html_safe
      <input type="hidden" name="authenticity_token" value="#{ form_authenticity_token }">
    HTML
  end

end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/views/coaches/index.html.erb
<h1>Hello, <%= @coach.email %></h1>
<h3>Upcoming Meets</h3>
<ul>
  <% @meets.each do |meet| %>
    <li><a href="<%= meet_url(meet) %>"><%= meet.meet_name %></a>: <time><%= meet.meet_date %></time></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwimEntry</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meets/show.html.erb
<h1><%= @meet.meet_name %></h1>

<form action="<%= meet_url(@meet) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="patch">
  <table>
    <thead>
      <th>First Name</th>
      <th>Last Name</th>
    </thead>

    <tbody>
      <tr>
        <td><input type="text" name="meet[swimmer][first_name]" value=""></td>
        <td><input type="text" name="meet[swimmer][last_name]" value=""></td>
      </tr>  
    </tbody>

  </table>
  <div class="submit">
    <input type="submit" value="Create Entries">
  </div>
</form>